"#-------------------------------------------------------\n"
"#   General setup\n"
"#-------------------------------------------------------\n"
"# Controls whether pseudo random sequence starts\n"
"#   with the same value, or with a time() value.\n"
"# This allows to repeat an experiment and obtain\n"
"#   the same resuls\n"
"#-------------------------------------------------------\n"
"SimulationIsRepeatable = YES\n"
"\n"
"\n"
"#-------------------------------------------------------\n"
"# Set this to \"YES\" if a K map was calculated and\n"
"#   you want to simply re-use it.\n"
"# Set it to \"NO\" if a K map file is not available,\n"
"#   for example if this is the 1st simulation of a city.\n"
"#-------------------------------------------------------\n"
"SkipCalibration = NO\n"
"\n"
"\n"
"#-------------------------------------------------------\n"
"#   Inputs\n"
"#-------------------------------------------------------\n"
"# Two images, grayscale; anything > 0.5 = urbanized\n"
"#-------------------------------------------------------\n"
"image1 = ./MyCity/Slide3.png\n"
"image2 = ./MyCity/Slide4.png\n"
"\n"
"#-----------------------------------\n"
"# Distance (years)= img2 - img1  (float accepted)\n"
"#-------------------------------------------------------\n"
"deltaTime = 3.0\n"
"\n"
"#------------------------------------------------\n"
"#  Roads\n"
"#------------------------------------------------\n"
"# One image, white pixel over black background)\n"
"# Will be used throughout simulation and forecast\n"
"#------------------------------------------------\n"
"roads  = ./MyCity/Roads.png\n"
"\n"
"\n"
"#------------------------------------------------\n"
"# Exclusion map\n"
"#------------------------------------------------\n"
"# One image, greyscale, black = non-urban\n"
"# Will be used throughout simulation and forecast\n"
"# Write NULL if there's no exclusion layer.\n"
"#------------------------------------------------\n"
"#exclusion  = /home/MyCity/Excluded.png\n"
"exclusion  = NULL\n"
"\n"
"\n"
"\n"
"#------------------------------------------------\n"
"# Distance map\n"
"#------------------------------------------------\n"
"# Map of plausible regions for 'spraying', computed as\n"
"#   distance to nearest urban pixel.\n"
"# Map is computed and saved, if file does not exist.\n"
"# Each pixel is adjusted as exp(-sigma*pixel).\n"
"#------------------------------------------------\n"
"DistanceMap   = ./PG/DistanceMap.png\n"
"sigma = 15.0\n"
"\n"
"\n"
"#-----------------------------------\n"
"#  Probability map\n"
"#-------------------------------------\n"
"# Map of plausible regions for 'spraying', computed with\n"
"#   heat equation.\n"
"# Map is computed and saved, if file does not exist.\n"
"# Define here number of heat cycles; the larger the number,\n"
"#   the more the map will be stretched.\n"
"PiMap   = ./PG/PiMap.png\n"
"HeatCyclesPiMap = 2000\n"
"\n"
"\n"
"#-----------------------------------\n"
"#  Execution options\n"
"#-------------------------------------\n"
"\n"
"\n"
"\n"
"#-------------------------------------\n"
"# Maximum number of calibration loops.\n"
"# Increase the value if you perceive that the calibration metric\n"
"#  has room to improve (=raise). Check screen output and log file.\n"
"MaxCalibrationLoops = 20\n"
"\n"
"\n"
"\n"
"#-------------------------------------\n"
"# Maximum number of heat equation cycles.\n"
"# Increase the value if you perceive that during calibration metric\n"
"#  has room to improve (=raise). Check screen output and log file.\n"
"MaxHeatCycles = 5000\n"
"\n"
"\n"
"#-------------------------------------\n"
"# The parameter gamma controls the amount of insulation against heat\n"
"#  that is deposited in every loop.\n"
"# A typical value would be 0.1\n"
"gamma = 0.08\n"
"\n"
"\n"
"#-------------------------------------\n"
"# Spray urbanization clusters in the hot (=plausible) map?\n"
"# This process creates 'clusters'.\n"
"# The size of clusters corresponds to the smaller cluster in image2.\n"
"# The number of clusters is the amount of new clusters from image1 to image2.\n"
"UrbanSprayForecast  = YES\n"
"\n"
"#-------------------------------------\n"
"#The K map shows the diffusion coefficient.\n"
"#It is initially set to 1, then it is gradually modified during calibration.\n"
"#The K map is perturbed with noise before forecast calculation;\n"
"#enter here the amount [0 ; 1]\n"
"KMapNoise = 0.3\n"
"SaveKMap = ./MyCity/KMap.png\n"
"\n"
"\n"
"\n"
"\n"
"#---------------------------------------\n"
"# Forecast years  (float accepted)\n"
"# This is a linear-regression parameter;\n"
"#    forecasts will approximate the city\n"
"#    size as if image1 - image2 - image3\n"
"#    follow a line.\n"
"#----------------------------------------\n"
"forecastTime = 3.0\n"
"\n"
"\n"
"#Output (required strings, do not leave blank)\n"
"#-------------------------------------\n"
"backgroundImg = NULL\n"
"simulationImg = ./MyCity/simulation.png\n"
"simulationErr = ./MyCity/simulationErr.png\n"
"forecastImg   = ./MyCity/forecast.png\n"
